INSERT INTO day (hour) VALUES(8);
INSERT INTO day (hour) VALUES(9);
INSERT INTO day (hour) VALUES(10);
INSERT INTO day (hour) VALUES(11);
INSERT INTO day (hour) VALUES(12);
INSERT INTO day (hour) VALUES(13);
INSERT INTO day (hour) VALUES(14);
INSERT INTO day (hour) VALUES(15);
INSERT INTO day (hour) VALUES(16);
INSERT INTO day (hour) VALUES(17);
INSERT INTO day (hour) VALUES(18);
INSERT INTO day (hour) VALUES(19);
INSERT INTO day (hour) VALUES(20);
INSERT INTO day (hour) VALUES(21);



